import "../globals.css";
import type { Metadata } from "next";
import { Almarai, Inclusive_Sans, Inter } from "next/font/google";
import { dir } from "i18next";
import { languages } from "../i18n/settings";

import { cn } from "@/lib/utils";

const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["300", "400", "700", "800"],
  variable: "--font-ar",
});

const inclusive_Sans = Inclusive_Sans({
  subsets: ["latin-ext"],
  weight: ["400"],
  variable: "--font-en",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((x) => x.value).map((lng) => ({ lng }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  return (
    <html lang={params.lng} dir={dir(params.lng)}>
      <body className={cn(inclusive_Sans.variable, almarai.variable)}>
        {children}
      </body>
    </html>
  );
}
